[workspace]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
homepage = "https://github.com/DenisGorbachev/standard-traits"
repository = "https://github.com/DenisGorbachev/standard-traits"
keywords = ["utils"]
categories = ["development-tools", "rust-patterns"]
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "AGENTS.ts",
    "CargoMetadata.ts",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.lock",
    "deno.json",
    "commitlint.config.mjs",
    "fnox.toml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[workspace.metadata.details]
name = "standard-traits"
title = "A collection of standard traits for better interoperability between crates"
readme = { generate = false }

[workspace.lints.rust]
redundant_imports = "deny"
unused_import_braces = "deny"
# unused_qualifications must not be "deny" because our code style has multiple `use Foo::*;`, and some macros (derive_more::Display, strum::Display, strum::EnumString) produce code with full qualifications
# unused_qualifications = "deny"

[workspace.lints.clippy]
absolute_paths = "deny"
arithmetic_side_effects = "deny"

[package]
name = "standard-traits"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A collection of standard traits for better interoperability between crates"
license = "Apache-2.0 OR MIT"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[package.metadata.details]
title = "A collection of standard traits for better interoperability between crates"

[lints]
workspace = true

[dependencies]
camino_1 = { package = "camino", version = "1.0.0", optional = true, default-features = false }
#fs_err_3 = { package = "fs-err", version = "3.0.0", optional = true, default-features = false }
indexmap_2 = { package = "indexmap", version = "2.0.0", optional = true, default-features = false }
proc_macro2_1 = { package = "proc-macro2", version = "1.0.0", optional = true, default-features = false }
syn_2 = { package = "syn", version = "2.0.0", optional = true, default-features = false }
tempfile_3 = { package = "tempfile", version = "3.0.0", optional = true, default-features = false }

[features]
default = ["std"]
std = []
unstable_get = []
unstable_of = []
camino_1 = ["dep:camino_1", "std"]
indexmap_2 = ["dep:indexmap_2"]
proc_macro2_1 = ["dep:proc_macro2_1"]
syn_2 = ["dep:syn_2", "std"]
syn_2_parsing = ["syn_2/parsing"]
syn_2_derive = ["syn_2/derive"]
syn_2_full = ["syn_2/full"]
tempfile_3 = ["dep:tempfile_3", "std"]
#fs_err_3 = ["dep:fs_err_3"]
